### PR TITLE
fixing bugs found by nickyd41

### PR DESCRIPTION
**Pull request by vsoch**
This PR will fix two bugs found by @nickyd41 identified in #1 

 - the delays.length is not long enough to go through the complete list, @nickyd41 reports that adding 1 to the loop iterator fixes the issue.
 - 60 months should have been 6 months

### CODE REVIEW

**Comment by vsoch** [comment]
@nickyd41 javascript uses 0 indexing, so if we loop from 0 to less than the length, that would be 0 through N-1, so that should cover the whole length of N. Did you try this without the second fix? Is the error perhaps something else?

**Comment by nickyd41** [comment]
I don't think it's a problem with the loop itself, especially because the others work as expected. However, I couldn't pinpoint where the error was originating

**Comment by vsoch** [comment]
okay I just restored (that top level loop). Could it be that the sub loop needs to go through a value higher than 5?

```bash
    for (var j = 0; j < 5; j++) {
      bickel_titrator_experiment.push(test_block);
      bickel_titrator_experiment.push(gap_block);
    }

```
I'm not familiar with the task, but it could be that "5" was hard coded at some point, and it needs to be the length of a variable.

**Comment by nickyd41** [comment]
I don't think it's due to the subloop...I believe the 5 is hard-coded to ensure that there are only 5 trials for each magnitude/delay combination

**Comment by vsoch** [comment]
okay, could you test with just this fix, and then tell me:

 1. the behavior that you see
 2. the behavior that you *should* see

I'm not hugely familiar with the task (and I'm a crappy psychology) so I can best help by approaching from a "it should be doing this thing but it's doing this thing" approach :) I'll also loop in the old repo maintainers in the case that they remember creating it (and have insight!)

**Comment by vsoch** [comment]
it looks like the bug was fixed in the upstream --> https://github.com/expfactory/expfactory-experiments/blob/master/bickel_titrator/experiment.js

Do you want to test that file, and see if the issue is resolved? If so, I'll update the experiment here with it!

**Comment by nickyd41** [comment]
Yep, issue has been fixed and it works as expected! Thank you!

**Comment by vsoch** [comment]
Great! Just to verify - you are referencing the experiment.js from the other repository (and not the fixed one here?) If the first is true, I'll copy that file here to this PR. If the second is true, I'll merge here. Let me know which one!

**Comment by nickyd41** [comment]
Yes, the experiment.js from https://github.com/expfactory/expfactory-experiments/blob/master/bickel_titrator/experiment.js

**Comment by vsoch** [comment]
okay, check it out now!

**Pull request merged**
